spring:
    datasource:
        url: jdbc:mysql://localhost:3306/er-sols
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    main:
      banner-mode: "off"
server:
  port: 8083

---
spring:
  profiles: docker-compose
  datasource:
      url: jdbc:mysql://trip-db:3306/trip-db
      username: root
      password: accounts
  jpa:
    show-sql: false
  rabbitmq:
    host: rabbitmq
server:
  port: 8080